# Generated by Django 4.2 on 2024-08-13 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='version',
            name='version_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Название версии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(default=None, verbose_name='Номер версии'),
            preserve_default=False,
        ),
    ]
