# Generated by Django 4.2 on 2024-08-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options_product_is_unpublish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('is_unpublish_product', 'Is unpublish product'), ('change_description_product', 'Change product description'), ('change_category_product', 'Change product category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
